yarnPath: .yarn/releases/yarn-3.4.1.cjs
# packageExtensions:
#     '@next/font@13.1.6':
#         peerDependencies:
#             'next': '13.1.6'
#         dependencies:
#             'next': '13.1.6'
# pnpMode: loose
